- name: Instal tools
  hosts: localhost
  become: yes
  vars_files:
    - vars.yaml
    - vars_secret.yaml
  tasks:

    - name: Tools Loop Start
      include_tasks: subplaybooks/include_tool.yaml
      loop: "{{ tools_playbooks }}"