- name: Install virtualbox
  apt:
    name: 
      - dkms
      - virtualbox
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Set debconf selections for virtualbox-ext-pack
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select

- name: Install virtualbox-ext-pack package
  apt:
    name: virtualbox-ext-pack
    state: latest
  environment:
    DEBIAN_FRONTEND: noninteractive