- name: Create Tools Directory in not exist
  include_tasks: subplaybooks/create_tools_dir.yaml

- name: Download PowerView File
  get_url:
    url: https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/master/Recon/PowerView.ps1
    dest: "{{ tools_directory }}"
    owner: "{{ kali_username }}"
    group: "{{ kali_username }}"
    force: true