- name: Create Tools Directory in not exist
  include_tasks: subplaybooks/create_tools_dir.yaml

- name: Download SharpUp File
  get_url:
    url: https://github.com/r3motecontrol/Ghostpack-CompiledBinaries/raw/master/SharpUp.exe
    dest: "{{ tools_directory }}"
    owner: "{{ kali_username }}"
    group: "{{ kali_username }}"
    force: true