- name: Create Tools Directory in not exist
  include_tasks: subplaybooks/create_tools_dir.yaml

- name: Clone deepsea-docker
  become_user: "{{ kali_username }}"
  git:
    repo: https://github.com/gifford-lab/deepsea-docker.git
    depth: 1
    clone: true
    force: true
    dest: "{{ tools_directory }}/deepsea-docker"