- name: Create Tools Directory in not exist
  include_tasks: subplaybooks/create_tools_dir.yaml

- name: Clone gitleaks
  become_user: "{{ kali_username }}"
  git:
    repo: https://github.com/gitleaks/gitleaks.git
    depth: 1
    clone: true
    force: true
    dest: "{{ tools_directory }}/gitleaks"

- name: Build gitleaks
  become_user: "{{ kali_username }}"
  make:
    chdir: "{{ tools_directory }}/gitleaks"
    target: build